### ISSUE TITLE
default google cloud configuration is more than default google account quota

### ISSUE THREAD

**Issue by jbayer** [pivotal-cf-experimental/lattice#19]
only the coordinator and cell-0 seem to be able to fit in the default google account quota according to the log output https://gist.github.com/jbayer/0cd0b966a06d07cbf333#file-gistfile1-txt-L107-L109

**Comment by jbayer** [comment]
i recommend defaulting it to 1 cell if that is the case

**Comment by dajulia3** [comment]
We changed the google cloud example template to only spin up one cell by default.
