### ISSUE TITLE
lattice-aws terraform apply: Error launching source instance

### ISSUE THREAD

**Issue by acrlewis** [pivotal-cf-experimental/lattice#23]
➜  lattice-aws  terraform apply
module.lattice-aws.aws_vpc.lattice-aws: Refreshing state... 
module.lattice-aws.aws_security_group.lattice-aws: Refreshing state... 
module.lattice-aws.aws_internet_gateway.lattice-aws: Refreshing state... 
module.lattice-aws.aws_subnet.lattice-aws: Refreshing state... 
module.lattice-aws.aws_route_table.lattice-aws: Refreshing state... 
module.lattice-aws.aws_route_table_association.lattice-aws: Refreshing state... 
module.lattice-aws.aws_instance.lattice-coordinator: Creating...
  ami:                        "" => "ami-d8a6c9b0"

module.lattice-aws.aws_instance.lattice-coordinator: Error: Error launching source instance: Not authorized for images: [ami-d8a6c9b0] (AuthFailure)
Error applying plan:

1 error(s) occurred:

* Error launching source instance: Not authorized for images: [ami-d8a6c9b0] (AuthFailure)

**Comment by acrlewis** [comment]
Looks like these are all deregistered or no longer available

variable "aws_image" {
    description = "The name of the image to base the launched instances."
    default = {
        ap-northeast-1 = "ami-cec3cbcf"
        ap-southeast-1 = "ami-d16a4483"
        ap-southeast-2 = "ami-974c27ad"
        eu-central-1 = "ami-1a3b0b07"
        eu-west-1 = "ami-88df64ff"
        sa-east-1 = "ami-7d77c460"
        us-east-1 = "ami-d8a6c9b0"
        us-west-1 = "ami-71c8d534"
        us-west-2 = "ami-992d7ea9"
    }
}

**Comment by dajulia3** [comment]
We're pushing a fix through, it will be on master once it runs through our pipeline. It is currently on the develop branch.

**Comment by acrlewis** [comment]
sweet

**Comment by dajulia3** [comment]
Landed in master

**Comment by acrlewis** [comment]
works, thanks brother
