### ISSUE TITLE
ltc start failed to add routers with today's tarball

### ISSUE THREAD

**Issue by df007** [pivotal-cf-experimental/lattice#25]
df@df-go:~/workspace/lattice$ ltc list
App Name	Instances	DiskMB		MemoryMB	Routes
lattice-app	1/1		1024		128		lattice-app.192.168.11.11.xip.io

http://10.0.2.15:8090/routes  shows:

{
doppler.192.168.11.11.xip.io: [
"10.0.2.15:8082"
],
loggregator.192.168.11.11.xip.io: [
"10.0.2.15:8070"
],
receptor.192.168.11.11.xip.io: [
"10.0.2.15:8888"
]
}

**Comment by davidwadden** [comment]
please try to download the ltc binary from the s3 repository (described at https://github.com/pivotal-cf-experimental/lattice-cli#platform--architecture--link) again, this was updated manually to the correct version.  we are looking into a bug with our CI that is uploading old version(s) of the binary, tracked under  https://www.pivotaltracker.com/story/show/88064364

**Comment by dajulia3** [comment]
We believe we have fixed the underlying issue in our continuous deployment pipeline. Thanks for reporting this!
