### ISSUE TITLE
hostname -I | awk '{ print $2 }' - doesn't work as expected inside test-kitchen; what was the expected format?

### ISSUE THREAD

**Issue by drnic** [pivotal-cf-experimental/lattice#5]
See https://github.com/pivotal-cf-experimental/lattice/blob/develop/common/setup/bootstrap#L40

On my test-kitchen vagrant VM, when working on https://github.com/drnic/lattice-ansible-playbook, `hostname -I` only returns a single value, the IP address. What is `hostname -I` returning on the Vagrant/non-AWS VM you're using?

**Comment by davidwadden** [comment]
In response to this, we'll support a LATTICE_SYSTEM_IP environment variable to set during vagrant up. This IP will be configured on the system instead of the default 192.168.11.11.

See https://www.pivotaltracker.com/story/show/85279384

**Comment by davidwadden** [comment]
This change went through CI and was promoted to master branch this morning

**Comment by drnic** [comment]
Ok, thanks guys.

On Fri, Jan 9, 2015 at 7:25 AM, davidwadden <notifications@github.com>
wrote:

> Closed #5 <https://github.com/pivotal-cf-experimental/lattice/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pivotal-cf-experimental/lattice/issues/5#event-216558458>
> .
>



-- 
Dr Nic Williams
Stark & Wayne LLC - consultancy for Cloud Foundry users
http://drnicwilliams.com
http://starkandwayne.com
cell +1 (415) 860-2185
twitter @drnic
