### ISSUE TITLE
How to manually build lattice tarball based on local dev version of repo?

### ISSUE THREAD

**Issue by drnic** [pivotal-cf-experimental/lattice#6]

**Comment by sykesm** [comment]
Any chance you can reference the Dockerfile used to generate cloudfoundry/lattice-pipeline or add it to the repo?

**Comment by dajulia3** [comment]
@sykesm the script and dockerfile used to generate the cloudfoundry/lattice-pipeline image is available here: https://github.com/pivotal-cf-experimental/lattice/tree/master/lattice-dependencies-pipeline/02_publish_pipeline_docker_image

**Comment by sykesm** [comment]
@dajulia3, thanks.
